### ISSUE TITLE
FATAL EXCEPTION: IntentService[ParsePushService]

### ISSUE THREAD

**Issue by alexpwer** [parse-community/Parse-SDK-dotNET#182]
Encountered the following error, which resulted in a crash. This occurred on Android using the latest release version of Parse (v1.7.0). Push notifications work correctly in within my app, but this seemed to happen at random. Unfortunately, I do not have an repo steps.

```
E/AndroidRuntime(27516): FATAL EXCEPTION: IntentService[ParsePushService]
E/AndroidRuntime(27516): Process: com.ingg.werfootball, PID: 27516
E/AndroidRuntime(27516): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
E/AndroidRuntime(27516): at com.parse.ParsePushService.onHandleIntent(ParsePushService.java:43)
E/AndroidRuntime(27516): at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime(27516): at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27516): at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(27516): at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by richardjrossiii** [comment]
Is this Unity android or Xamarin android? They have completely different push notification subsystems sadly.

**Comment by alexpwer** [comment]
This is Unity Android

**Comment by montymxb** [comment]
Without step to reproduce we can't really address this :/. If you have steps post them here and let me know so I can open this back up.
