### ISSUE TITLE
ParsePush.subscribeAsync("") throwing TargetInvocationException on Windows Phone 8

### ISSUE THREAD

**Issue by esfilho** [parse-community/Parse-SDK-dotNET#49]
I'm using VS Express for Windows Phone 2012 to develop my Windows Phone 8 apps.
I followed the WP8 quickstart guide and did everything right.

I'm using the latest relaease (1.6.1).

Here is my code:

```
ParseClient.Initialize("AppKey". "DotNetKey");
await ParsePush.SubscribeAsync("");
await ParseAnalytics.TrackAppOpenedAsync();
```

Any ideas why it's throwing the Exception?

**Comment by richardjrossiii** [comment]
Can you perhaps post the stack trace of the exception here?

**Comment by esfilho** [comment]
Sure, sorry about that.

```
_innerException	{Parse.ParseException: Invalid response from server ---> System.ArgumentException: Input JSON was invalid.
   at Parse.Internal.Json.Parse(String input)
   at Parse.Internal.ParseCommandRunner.<>c__DisplayClass2.<RunCommandAsync>b__1(Task`1 t)
   --- End of inner exception stack trace ---
   at Parse.Internal.ParseCommandRunner.<>c__DisplayClass2.<RunCommandAsync>b__1(Task`1 t)
   at Parse.Internal.InternalExtensions.<>c__DisplayClass1`2.<OnSuccess>b__0(Task t)
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SRLib.LauncherPage.<RegisterForPushNotifications>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)}	System.Exception {Parse.ParseException}
```

**Comment by esfilho** [comment]
@richardjrossiii Still not able to use parse in WP8.
Any news here?

Thanks in advance

**Comment by hhartz** [comment]
@richardjrossiii I'm experiencing the same issue. Can you provide a workaround for this? Seems this has also gone unanswered here; https://parse.com/questions/unable-to-push-notifications-to-wp8-through-the-dashboard

**Comment by esfilho** [comment]
@hhartz @richardjrossiii 
In Lumia 520 with WP 8.1, it crashes.
In Lumia 530 with WP 8.1, it doesn't crash but the notifications don't arrive in the device.

**Comment by montymxb** [comment]
Closing as out of date.
